### ISSUE TITLE
Brotli requires nginx 1.16, I have nginx 1.17

### ISSUE THREAD

**Issue by pnoeric** [eustas/ngx_brotli#35]
Hi, I'm having a problem with `yum install nginx nginx-module-nbr`... it appears that I have nginx 1.17, but the Brotli plugin requires 1.16. Is that correct? And if so, is there a newer Brotli plugin I can install?

```
# yum install nginx nginx-module-nbr

Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.mojohost.com
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirror.mojohost.com
 * nux-dextop: mirror.li.nux.ro
 * updates: mirror.mojohost.com
 * webtatic: us-east.repo.webtatic.com
Package 1:nginx-1.17.2-1.el7.ngx.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package nginx-module-nbr.x86_64 1:1.16.0.0.1.2-1.el7.gps will be installed
--> Processing Dependency: nginx = 1:1.16.0-1.el7.ngx for package: 1:nginx-module-nbr-1.16.0.0.1.2-1.el7.gps.x86_64
--> Finished Dependency Resolution
Error: Package: 1:nginx-module-nbr-1.16.0.0.1.2-1.el7.gps.x86_64 (getpagespeed-extras)
           Requires: nginx = 1:1.16.0-1.el7.ngx
           Installed: 1:nginx-1.17.2-1.el7.ngx.x86_64 (@nginx)
               nginx = 1:1.17.2-1.el7.ngx
```

**Comment by denji** [comment]
This is not the official RPM package of eustas/ngx_brotli I would not even be surprised if there are "untrusted code". For all questions, you can ask the maintainer packages (*.getpagespeed.com) @dvershinin

**Comment by denji** [comment]
This is not the official `eustas/ngx_brotli` RPM package.
For all questions, you can ask the maintainer packages (*.getpagespeed.com) @dvershinin

**Comment by pnoeric** [comment]
Hi @denji -- thank you -- yet I am still confused by all of this. :-)

There is, somewhere, a Brotli "plugin" (module) for Nginx. It supports only Nginx 1.16.

The official one appears to be here https://github.com/google/brotli... though it also appears totally dead (nice job Google). Many posts there refer me to here, https://github.com/eustas/nginx-brotli. But I realize this isn't the official version. That said, it does seems to be maintained, at least more than the official Google one.

You mentioned @dvershinin who has a site GetPageSpeed (which is awesome). On that site he offers a [module called 'nginx-extras'](https://www.getpagespeed.com/nginx-extras) that appears to be one module with Brotli and a bunch of other things. Which is great and pretty cool, but more than what I'm seeking.

Is anyone maintaining the official, standalone, nginx-brotli plugin any longer?!

**Comment by dvershinin** [comment]
@pnoeric I think you're confusing few things there. Namely source repository vs RPM packages repository.

Source (GitHub, where code is hosted): there is one official repository, and that is [google/ngx_brotli](https://github.com/google/ngx_brotli). For reason largely unknown it was "abandoned", and this eustas/ngx_brotli seems like a continuation of it, maintained by a Google employee (AFAIK), has more fixes/updates compared to the official. So more or less it can be considered official for all intents.

RPM (where binary builds for the module hosted): The only official repository for binary builds would be the one for [Nginx Plus](https://docs.nginx.com/nginx/admin-guide/dynamic-modules/brotli/). Naturally, it requires you to have Nginx Plus.

If you don't make use of Nginx Plus, your choices are either:

## 1. Build the module yourself. 

This puts a requirement of: 

* setting up the build environment (and keeping it secure, it should go without saying that installing compilation software on production systems should be avoided).
* having to rebuild the module for each new release
* dealing with SELinux issues if you custom compile/install NGINX to non-standard (per policy) locations; unfortunately, most of people just end up disabling SELinux altogether 

## 2. Use community packages/repositories

In my line of work, I install and configure servers. NGINX supported dynamically loadable modules for years now, but I only saw the community creating some monster NGINX builds where modules are compiled in statically.

So I saw it's a natural path for me to compile/package modules separately. This is what Nginx Plus does and I built the same + [a bit more](https://extras.getpagespeed.com/redhat/7/x86_64/repoview/nginx-extras.group.html), and put it for public use.

The GetPageSpeed repository is in no way official and you bear the risks associated with using a third-party repository like GetPageSpeed extras repository.

The modules there are built for NGINX stable branch (you use mainline), which is why it doesn't work for you. If you switch to use of stable NGINX, you can then install the package normally. 

The choice to build modules for stable branch of NGINX was due to likely better "code API compatibility" and greater availability of modules that successfully compile for it.

You don't need to install all of the modules. In theory and in practice you can:

* Add nginx stable repository to your system and set it to be of highest priority with yum options
* Add GetPageSpeed extras repository
* Then install `nginx-module-nbr` - result would be that `nginx` binary package will be fetched from official repository, while the module will be fetched from extras.getpagespeed.com

**Comment by dvershinin** [comment]
P.S. nginx-extras is not a module that installs everything, but merely a collection of those. You can install NGINX with just the modules you want, as in `yum install nginx-module-<module name>`, similar to Nginx Plus.

**Comment by pnoeric** [comment]
Thank you very much @dvershinin  - this is really the most awesome, clear, and useful explanation of what's going on and all the different moving parts. (Truly: I wish your post was on the front page of both the official brotli repo and the front page of this repo.... it provides the **context** that was missing.) I appreciate you taking the time to explain it all.

So, ok, I get it. Nobody out there has compiled brotli as as standalone module for my specific version of nginx. Sounds like I should look at changing to the stable branch of nginx and then I can also enjoy all those sexy things you're doing at getpagespeed.com.

**Comment by dvershinin** [comment]
@pnoeric building mainline packages is something I had in mind, however, it's not as sexy as stable because updates are not super-automatic for now. 

Still, it might be worth trying to install the package from the "mainline" repo I built today (has only brotli module for now).

Try these steps to install the module package for the mainline NGINX:

    yum -y install yum-utils
    yum clean all && yum update getpagespeed-extras-release
    yum-config-manager --enable getpagespeed-extras-mainline
    yum install nginx-module-nbr

**Comment by eustas** [comment]
This fork is merged back to google/ngx_brotli. Please recreate this issue there (if necessary).
